name: Check features matrix compiles
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  all-features:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache cargo build artifacts
      uses: ./.github/actions/cargo-cache
      with:
        shared-key: "all-features"

    - run: cargo install cargo-all-features
    - name: Check all lib features
      run: |
        cd smt-scope-lib
        RUSTFLAGS="-D warnings" cargo check-all-features -- --release
    - name: Check all gui features
      run: |
        cd smt-scope-gui
        RUSTFLAGS="-D warnings" cargo check-all-features -- --release
