name: Continuous integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup `Cargo.lock` for caching
      run: cargo generate-lockfile
    - name: Cache cargo
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "all-features"
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - run: cargo install cargo-all-features
    - run: RUSTFLAGS="-D warnings" cargo check-all-features --release
